FROM apache/airflow:2.9.2-python3.11

# FROM python:3.11-slim
USER root

# Install dependencies
RUN apt-get update \
  && apt install unzip -y\
  && apt-get install -y --no-install-recommends \
         vim gnupg2 libnss3-dev wget\
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* 
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \ 
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
RUN apt-get update && apt-get -y  --fix-missing install google-chrome-stable

COPY requirements_airflow.txt /opt/airflow/requirements.txt

USER airflow

RUN pip3 install --no-cache-dir -r requirements.txt